// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";


import Link from "next/link";
import NavBar from "./components/NavBar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const [globalIsAuthorized] = useState(false);

  // initial load:
  //   fetch('/auth')
  //     .then(
  //       set global isAuthorized(true)
  //     )


  //   useEffect(() => {

  //   }, [])

  return (
    <html lang='en'>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <nav>
          <Link href='/'>Home</Link>
          <Link href='/login'>Login</Link>
          <Link href='/signup'>Sign up</Link>
          <Link href='/users'>Users</Link>
        </nav> */}

          
          <NavBar/>


        {children}
      </body>
    </html>
  );
}
