const express = require('express');
const app = express();
const port = 4567;

let champs = ['Zed', 'LeBlanc', 'Ahri'];
const notSoSecret = 'ehehe:D';

// middlewares
app.use(express.json()) // parsing json
app.use(express.urlencoded()) // form


const users = [
    {
        name: 'duy',
        isloggedin: true
    },
    {
        name: 'hoang',
        isloggedin: false
    }
];



// custom middleware

const logRequest = (req, res, next) => {

    const date = new Date(Date.now()).toLocaleString("en-GB", { timeZone: "UTC" });
    const method = req.method;
    console.log(`[${date}] 🚀 Receive a ${method} request at: ${req.originalUrl}`);
    
    next(); // request successful. move on to the next handler
}


// app scope
app.use(logRequest);

// hijacked
// app.use(makeErrorRequest)


// middleware to protect route
const loggedInRequired = (req, res, next) => {
    // session / token

    console.log('>> loggedInRequired middleware');
    
    console.log('headers:', req.headers);

    const { authorization } = req.headers;

    console.log(authorization);
    

    if (authorization !== notSoSecret) {
        return next('WHERE THE SECRET BRO???');
    }
    
    return next();
    
}


const isAuthor = (req, res, next) => {
    const { username } = req.headers;
    
    if (!username) return next('Missing username');

    if (username !== 'hehe') return next('Wrong username');

    return next();
}


// server <- token -> client



// app.use(loggedInRequired);

const name = 'heheahah';
const img = 'https://m.media-amazon.com/images/I/813kqvYoRfL.png';


// Server-side rendering
app.get('/', (req, res) => {
    const html = `
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Rendered by Express</title>
        </head>
        <body>
            <h1>Hello</h1>
            <p>Welcome to my website</p>
            <p>My name is ${name}</p>
            <p>This site is generated by Express</p>
            <img src="${img}" alt="hehe" width="200px" />

            <button onclick="clickme()">Click me</button>

            <script>
                const clickme = () => {
                    alert('sup bro??');
                };
            </script>
        </body>
        </html>
    `;

    return res.send(html);
});





// Handle all other requests for ALL methods
// Custom error handling
app.use((req, res) => {
    res.status(404).send('<h1>404 not found :(</h1>');
});



app.listen(port, () => {
  console.log(`Example app listening on port http://localhost:${port}`);
});
