--Q1 Q2
SELECT Mvtitle FROM Movie;

--Q3
SELECT COUNT(*) AS TotalMovies FROM Movie;

--Q5
SELECT MVTITLE, MVTYPE
FROM Movie
WHERE MVTYPE = 'HORROR' AND NOMS > 0;

--Q6
SELECT MVTITLE, MVTYPE, NOMS
FROM Movie
WHERE (MVTYPE = 'HORROR' AND NOMS > 0) OR MVTYPE = 'COMEDY';

--Q7
SELECT MVTITLE, MVTYPE, NOMS
FROM Movie
WHERE (MVTYPE = 'HORROR' AND NOMS > 0) OR (MVTYPE = 'COMEDY' AND NOMS > 0);

--Q9
SELECT MVTITLE
FROM Movie
WHERE MVTITLE LIKE '%nuremberg';

--%: wild card character


